name: DevSecOps CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'


      - name: Give permission to mvnw
        run: chmod +x mvnw
        working-directory: board


      - name: Build Application
        run: ./mvnw clean package -DskipTests
        working-directory: board


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Docker Image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_TAG=$(date +%s)

          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build -t $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
        working-directory: board


      - name: Push Image to ECR
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG


      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/


      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER_NAME }}


      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f board/k8s/namespace.yaml
          kubectl apply -f board/k8s/deployment.yaml
          kubectl apply -f board/k8s/service.yaml


      - name: Update Deployment Image
        run: |
          kubectl set image deployment/train-ticket-deployment \
          train-ticket-container=$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG \
          -n game-ns

          kubectl rollout status deployment/train-ticket-deployment \
          -n train-ticket --timeout=200s
